include dracula.conf

font_family      JetBrainsMono Nerd Font Mono
font_size        12.0
bold_font        JetBrainsMono Nerd Font Mono Extra Bold
bold_italic_font JetBrainsMono Nerd Font Mono Extra Bold Italic

# --- Quality of life ---
enable_audio_bell    no
visual_bell_duration 0
confirm_os_window_close 0
scrollback_lines              10000
scrollback_pager_history_size 100
repaint_delay   8
input_delay     2
sync_to_monitor yes

# --- macOS ---
macos_option_as_alt                left
hide_window_decorations            titlebar-only
macos_titlebar_color               background
macos_quit_when_last_window_closed yes

# --- Remote control + shell integration ---
allow_remote_control yes
listen_on            unix:/tmp/kitty-{kitty_pid}
shell_integration    enabled

# --- Visual ---
window_padding_width 6
cursor_trail         3
tab_bar_edge         top
tab_bar_style        powerline
tab_powerline_style  slanted
